In [1]:
import numpy as np

In [27]:
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]
])

In [28]:
# i:
print(arr[1])

[50 60 70 80]


In [29]:
# ii:
print(arr[:2, 1:3])

[[20 30]
 [60 70]]


In [30]:
# iii:
print(arr[:, -1])

[ 40  80 120]


In [31]:
arr[1,:] = [1,2,3,4]

In [32]:
print(arr)

[[ 10  20  30  40]
 [  1   2   3   4]
 [ 90 100 110 120]]
