In [8]:
# PART 2:

In [9]:
import numpy as np


In [16]:
# a)
ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(ar)
print(ar.ndim)
print(ar.shape)
print(ar.size)
print(type(ar))

[ 1  2  3  4  5  6  7  8  9 10]
1
(10,)
10
<class 'numpy.ndarray'>


In [18]:
# b)
arr = np.arange(1,10).reshape(3,3)
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(type(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
9
<class 'numpy.ndarray'>


In [ ]:
# c)
flo_ar = np.array([[1.2, 2.5, 3.8],[4.1, 5.9, 6.3],[7.7, 8.4, 9.6]])
int_ar = flo_ar.astype(int)
print(int_ar)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
