In [1]:
import numpy as np

Question 1

In [ ]:
#  i:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]
])

In [4]:
add = A + 10

In [5]:
print(add)
print(add.shape)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
(3, 3)


In [6]:
# ii:
row = np.array([1, 2, 3])
add2 = A + row


In [8]:
print(add2)
print(add2.shape)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
(3, 3)


In [10]:
# iii:
col = np.array([[1],
                [2],    
                [3]
])

In [11]:
add3 = A + col

In [12]:
print(add3)
print(add3.shape)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
(3, 3)
