In [1]:
import numpy as np

In [ ]:
# Question 1
arr = np.arange(1,13).reshape(3,4).reshape(2,6)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [4]:
# Question 2
two = np.array([[1, 2, 3], 
                  [4, 5, 6]
])


In [5]:
flat = two.flatten()
print(flat)

[1 2 3 4 5 6]


In [6]:
ravel = two.ravel()
print(ravel)

[1 2 3 4 5 6]


In [7]:
# Question 3
arr2 = np.arange(1, 10).reshape(3, 3)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
flat2 = arr2.flatten()
print(flat2)

[1 2 3 4 5 6 7 8 9]


In [9]:
ravel2 = arr2.ravel()
print(ravel2)

[1 2 3 4 5 6 7 8 9]


In [10]:
ravel2[0] = 999
print(ravel2)

[999   2   3   4   5   6   7   8   9]
