In [1]:
import numpy as np

In [3]:
# a)
zero = np.zeros((4,4))
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
# b)
one = np.ones((3,2))
print(one)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
# c)
ident = np.eye(5)
print(ident)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
# d)
full = np.full((3,3),7)
print(full)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
# e)
rand = np.random.randint(10, 100, (3,4))
print(rand)

[[13 98 46 28]
 [34 27 52 75]
 [36 92 72 94]]


In [14]:
# Q2
arra = np.arange(5,50, 5).reshape(3,3)
print(arra)


[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
